- id: ding_front_doorbell
  alias: Ding Front Doorbell
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: group.speakers
      volume_level: '0.7'
    service: media_player.volume_set
  - data:
      entity_id: group.speakers
      media_content_id: https://dl.dropboxusercontent.com/s/tf344hbx9nlxc3e/doorbell-easy.mp3?dl=0
      media_content_type: audio/mp3
    service: media_player.play_media