- id: ding_front_doorbell
  alias: Ding Front Doorbell
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      volume_level: '0.7'
    service: media_player.volume_set
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      media_content_id: https://dl.dropboxusercontent.com/s/tf344hbx9nlxc3e/doorbell-easy.mp3?dl=0
      media_content_type: audio/mp3
    service: media_player.play_media
- id: lulu_arriving_home
  alias: Lulu arriving home
  trigger:
  - entity_id: device_tracker.lulu
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - wait_template: '{{ is_state(''script.welcome_greetings'', ''off'') }}'
  - data:
      entity_id: input_boolean.lulu_arrived
    service: input_boolean.turn_on
- id: mama_arriving_home
  alias: Mama arriving home
  trigger:
  - entity_id: device_tracker.mama
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - wait_template: '{{ is_state(''script.welcome_greetings'', ''off'') }}'
  - data:
      entity_id: input_boolean.mama_arrived
    service: input_boolean.turn_on
- id: papa_arriving_home
  alias: Papa arriving home
  trigger:
  - entity_id: device_tracker.papa
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - wait_template: '{{ is_state(''script.welcome_greetings'', ''off'') }}'
  - data:
      entity_id: input_boolean.papa_arrived
    service: input_boolean.turn_on
- id: yiyi_arriving_home
  alias: Yiyi arriving home
  trigger:
  - entity_id: device_tracker.yiyi
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - wait_template: '{{ is_state(''script.welcome_greetings'', ''off'') }}'
  - data:
      entity_id: input_boolean.yiyi_arrived
    service: input_boolean.turn_on
- id: welcome_home_greeting
  alias: Welcome Home greeting
  trigger:
  - entity_id: input_boolean.lulu_arrived
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: input_boolean.mama_arrived
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: input_boolean.papa_arrived
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: input_boolean.yiyi_arrived
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: script.welcome_greetings
    service: script.turn_on
