- id: ding_front_doorbell
  alias: Ding Front Doorbell
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      volume_level: '0.6'
    service: media_player.volume_set
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      media_content_id: https://dl.dropboxusercontent.com/s/tf344hbx9nlxc3e/doorbell-easy.mp3?dl=0
      media_content_type: audio/mp3
    service: media_player.play_media
- id: lulu_arriving_home
  alias: Lulu arriving home
  trigger:
  - entity_id: device_tracker.lulu
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      volume_level: '0.5'
    service: media_player.volume_set
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      message: Welcome home Lulu
    service: tts.google_say
  initial_state: true
- id: mama_arriving_home
  alias: mama arriving home
  trigger:
  - entity_id: device_tracker.mama
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      volume_level: '0.5'
    service: media_player.volume_set
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      message: Welcome home Mama
    service: tts.google_say
  initial_state: true
- id: papa_arriving_home
  alias: papa arriving home
  trigger:
  - entity_id: device_tracker.papa
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      volume_level: '0.5'
    service: media_player.volume_set
  - data:
      entity_id: media_player.lulus_home_mini_speaker
      message: Welcome home Papa
    service: tts.google_say
  initial_state: true
  